### PR TITLE
Fix Add_species eventtargettoappend

### PR DESCRIPTION
**Pull request by trinetramv**

### CODE REVIEW

**Comment by trinetramv** [comment]
Sorry, was trying new pull request and didn't add any files.

**Comment by trinetramv** [comment]
New Updates :
  - **Added telemetry for**

                   - Clear All 
                   - Reset 
                   - Play
                   - Pause
                   - Add_arrow
                   - Remove_arrow
                   - Remove_species
 - **Edited Clear all label to Clear All**

[insights-biome-updated.zip](https://github.com/paulgrudnitski/insights-biome/files/246625/insights-biome-updated.zip)

**Comment by paulgrudnitski** [comment]
@trinetramv - I don't understand what you are doing here.  Did you update the biome simulations?  All 4 of them?  I guess I don't see the changes.  Why did you attach insights-biome-updated.zip?

**Comment by armingutzmer** [comment]
The vendor had some problem updating the repository.  I don't know what.
They emailed me updated sims.

I was going to dig into it tomorrow.

*Armin Gutzmer*

Senior Technical Project Manager
Content Systems

Assessment & Information
Pearson

D: (512) 989-5000  x224110
M: (512) 626-3209

**Comment by paulgrudnitski** [comment]
Perhaps the fact that trinetramv is not a listed Collaborator (until now) would make it very difficult to commit code.

**Comment by armingutzmer** [comment]
So they were using the wrong login?  They are proly arriving at work now.
I can ping them and ask them to try again now.

*Armin Gutzmer*

Senior Technical Project Manager
Content Systems

Assessment & Information
Pearson

D: (512) 989-5000  x224110
M: (512) 626-3209

**Comment by paulgrudnitski** [comment]
@santoshgururaj was added as a collaborator.

@trinetramv was not added as a collaborator...until just now.  It looks like @trinetramv is trying to commit code, not @santoshgururaj.

Would be very helpful to know if this is what prevented @trinetramv from committing code.

**Comment by armingutzmer** [comment]
That's probably it.  I will send that info to them now and ask them to try
again.

*Armin Gutzmer*

Senior Technical Project Manager
Content Systems

Assessment & Information
Pearson

D: (512) 989-5000  x224110
M: (512) 626-3209

**Comment by armingutzmer** [comment]
Are you wanting the updated sims now?   I can email them to you.

Otherwise I am emailing the vendor and I'll ping them on skype before I
head to bed if I see them.

*Armin Gutzmer*

Senior Technical Project Manager
Content Systems

Assessment & Information
Pearson

D: (512) 989-5000  x224110
M: (512) 626-3209

**Comment by paulgrudnitski** [comment]
Please...**COMMIT the updated sims** to the repo.  Enough of the emailing of sims and items.

**Comment by armingutzmer** [comment]
If they don't I will, but I need to step thru it with Jeff in the morning.

*Armin Gutzmer*

Senior Technical Project Manager
Content Systems

Assessment & Information
Pearson

D: (512) 989-5000  x224110
M: (512) 626-3209

**Pull request closed without merging**
